### ISSUE TITLE
Make it faster

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/shaperglot#9]
Need a speedup of about 60x.

**Comment by NeilSureshPatel** [comment]
Not sure if this is a useful, but I was thinking that for a lot of the tests we want we are looking at the same input string. For example running an orthographies check and then repeating it with smcp enabled. It makes me wonder if there is a run time benefit to not reloading the input string between those tests.

**Comment by simoncozens** [comment]
Right, or caching the results. Or shaping *all* the characters at once with Harfbuzz, and then sorting out the results. There are lots of things we can do.

**Comment by simoncozens** [comment]
One reason you're finding shaperglot slow is that you're running a new Python process (loading all the libraries, reading the font, etc.) for each script. I'll send you a PR which uses shaperglot as a library; that should speed things up significantly.

**Comment by NeilSureshPatel** [comment]
Thanks Simon. Just gave it a run and its super fast.  From: Simon CozensSent: Friday, November 4, 2022 5:24 AMTo: simoncozens/shaperglotCc: Neil S Patel; CommentSubject: Re: [simoncozens/shaperglot] Make it faster (Issue #9) One reason you're finding shaperglot slow is that you're running a new Python process (loading all the libraries, reading the font, etc.) for each script. I'll send you a PR which uses shaperglot as a library; that should speed things up significantly.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
